name: pcb-artifacts

on:
  push:
    paths:
    - 'OeMRFM69_USB/PCB/**.kicad_sch'
    - 'OeMRFM69_USB/PCB/**.kicad_pcb'
    - '.github/workflows/pcb-artifacts.yaml'
  pull_request:
    paths:
    - 'OeMRFM69_USB/PCB/**.kicad_sch'
    - 'OeMRFM69_USB/PCB/**.kicad_pcb'
    - '.github/workflows/pcb-artifacts.yaml'
  workflow_dispatch:

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest

    steps:
    - name: Update system repositories, Install Required Libraries and Initialize git-lfs
      run: |
        apt update
        apt -y install git git-lfs zip librsvg2-bin imagemagick
        git lfs install

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Running on branch
      run: |
        echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"
  
    - name: Date PCB
      run: |
        export DDDD=$(date)
        echo "DDDD = ${DDDD}"
        sed -i "s!<<date>>!${DDDD}!" OeMRFM69_USB/PCB/OeMRFM69_USB.kicad_pcb
  
    - name: Update the PCBs with on default branch with git hash
      if: steps.branch-name.outputs.is_default == 'true'
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!${COMMIT}!" OeMRFM69_USB/PCB/OeMRFM69_USB.kicad_pcb

    - name: Update the PCBs with the git hash and BETA.
      if: steps.branch-name.outputs.is_default != 'true'
      run: |
        export COMMIT=$(git rev-parse --short HEAD)
        echo "COMMIT = ${COMMIT}"
        sed -i "s!<<hash>>!BETA-${COMMIT}!" OeMRFM69_USB/PCB/OeMRFM69_USB.kicad_pcb

    - name: Remove existing export folder
      run: |
        rm -rf ./OeMRFM69_USB/PCB/export/

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: ./OeMRFM69_USB/PCB/config-2layer.kibot.yaml
        dir: ./ModuleV490-PassiveBal/export
        schema: './OeMRFM69_USB/PCB/OeMRFM69_USB.kicad_sch'
        board: './OeMRFM69_USB/PCB/OeMRFM69_USB.kicad_pcb'

    # Splitting this out to ensure a failed kibot run will mark a check as failed.
    - name: Prepare Gerbers artifact
      run: |
        cd ./OeMRFM69_USB/PCB/export/gerbers
        zip -r -j ../OeMRFM69_USB_gerbers.zip *        

    - name: Remove gerber folder
      run: |
        rm -rf ./OeMRFM69_USB/PCB/export/gerbers
  
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      if: steps.branch-name.outputs.is_default != 'true'
      with:
        name: OeMRFM69_USB_gerbers
        path: |
          ./OeMRFM69_USB/PCB/export/OeMRFM69_USB_gerbers.zip
